version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: "mylib.amarcreation.xyz"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - echo Build started on ENV `${BUILD_ENV}`
            - ng build --env=${BUILD_ENV}
    post_build:
         commands:
            - aws s3 rm s3://${S3_BUCKET} --recursive
            - echo S3 bucket is cleared.
            - aws s3 cp dist/MyLibraryDemo s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
